In [1]:
import pandas as pd
import numpy as np
import numpy as geek
import random
import math
from scipy import linalg

In [2]:
df= pd.read_excel(r'C:\Users\Shrey Kulkarni\Desktop\ASSIGNMENT 5\Dataset_5.xlsx')
df=df.drop(['X','Y'],axis=1)
columns = list(df.columns)
samples = columns[:len(columns)]
class_labels = list(df[columns[-1]])

In [3]:
df[0:10]

S       R
0  5.5607  5.1980
1  2.8222  4.6723
2  3.8615  5.2383
3  7.4969  4.7704
4  6.3981  5.6169
5  5.2551  4.7252
6  4.8356  4.3989
7  4.2523  4.9077
8  3.4237  5.6086
9  5.4809  5.7371

In [4]:
#Initialising fuzzy c_means variables

#Length of df
N=len(df)

#No of features
n=2

#No of clusters
c =5

#Fuzzy parameter
m=2        

#Error threshold
e=0.001

L=0

Z=df.values
Z=np.array(Z)
Z=Z.transpose()
print(Z)

[[5.5607 2.8222 3.8615 ... 0.     0.     0.    ]
 [5.198  4.6723 5.2383 ... 3.2135 0.0236 0.6489]]


In [5]:
#Membership function
#Randomly generating a list of length "c"
#Then normalizing the list
#Then appending the normalized list in an empty array U
U=np.empty((c,1),dtype=int)
for k in range (N):
    random_num_list = [random.random() for i in range(c)] 
    summation = sum(random_num_list)
    temp_list = [x/summation for x in random_num_list]
    temp_list=np.array(temp_list)
    temp_list = np.reshape(temp_list,(c,1))
    global U
    U=np.append(U,temp_list,axis=1)
#Since first column is zeros, we remove that
U=U[:,1:]
print(U)


[[0.26962108 0.28493176 0.09047161 ... 0.13778381 0.04234412 0.2406264 ]
 [0.28639646 0.2838377  0.35586679 ... 0.05001833 0.28215279 0.33854622]
 [0.10440798 0.08738222 0.07534265 ... 0.2329521  0.24060936 0.30041948]
 [0.16012107 0.15515686 0.36949134 ... 0.15309312 0.39986749 0.03028778]
 [0.17945341 0.18869147 0.1088276  ... 0.42615264 0.03502624 0.09012012]]


In [6]:
#Initializing an empty array U_updated of c rows and 800 columns.
U_updated=np.zeros(((c,800)),dtype=float)
print(U_updated)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
while True: 
    global U
    global U_updated
    global A
    global B
    global J
    diff=0
#Cluster centroids V[i]
    print("Initial matrix:", U)
    U_updated=np.zeros(((c,800)),dtype=float)
    V=[]
    def clustermeans(U,Z):
        global numer
        global denom
        global V
        for i in range (c):
            numer=0
            denom=0
            for k in range (N):
                numer+= math.pow(U[i][k],m)*Z[:,k].reshape(2,1)     
                denom+=  math.pow(U[i][k],m) 
                                       
            q = (numer)/(denom)
 
            
                                                                    
            V.append(q)  
        V=(np.array(V).transpose()).reshape(2,c)
                                  
        return V
    print("The cluster centroids are:",clustermeans(U,Z))
    

#Distance
    d=[]
    def D(i,k):
        h =np.subtract((Z[:,k].reshape(2,1)),(V[:,i]).reshape(2,1))
        d= (h.transpose()).dot(h)                      
        return d     
        
    print("The distance is:",D(1,1))
    
    J=0
    for i in range (1,c):
        for k in range (1,N):
            J += (math.pow(U[i][k],m))*(abs(D(i,k)))
    print("The cost function value is:",J,  c)
    

#Updating matrix
    k_list=[]
    for i in range(c):
        for k in range(N):
            if (D(i,k)>0):
                A=0
                B=0
                for j in range(c):
                    A=A+math.pow((D(i,k)/D(j,k)),(1/(m-1)))
                U_updated[i][k]=1/A

            else:
                k_list.append(k)
                current_r=i
                for row in range(c):
                    if (row == current_r):
                        U_updated[row][k]=1
                    else:
                        U_updated[row][k]=0


    
    print("New matrix", U_updated)  

    
    
    L=L+1
    print(L)
    diff=np.subtract(U, U_updated)
    print("The difference is:",linalg.norm(diff),diff)
    U=U_updated
    if (linalg.norm(diff)<e):
        break
    


Initial matrix: [[0.26962108 0.28493176 0.09047161 ... 0.13778381 0.04234412 0.2406264 ]
 [0.28639646 0.2838377  0.35586679 ... 0.05001833 0.28215279 0.33854622]
 [0.10440798 0.08738222 0.07534265 ... 0.2329521  0.24060936 0.30041948]
 [0.16012107 0.15515686 0.36949134 ... 0.15309312 0.39986749 0.03028778]
 [0.17945341 0.18869147 0.1088276  ... 0.42615264 0.03502624 0.09012012]]
The cluster centroids are: [[ 0.09872164 -0.1882876   0.07231524  0.01158494  0.21123085]
 [ 0.083055    0.35738127 -0.17127549  0.21116469  0.11333208]]
The distance is: [[27.68155927]]
The cost function value is: [[6525.13476219]] 5
New matrix [[0.20099445 0.19988264 0.20034251 ... 0.19390021 0.49357417 0.1440473 ]
 [0.19926294 0.20563721 0.20288714 ... 0.23215939 0.0446343  0.39461014]
 [0.1909173  0.18349372 0.18708609 ... 0.16594501 0.15171728 0.07010446]
 [0.20220293 0.20475163 0.20354605 ... 0.2110072  0.18561916 0.24785353]
 [0.20662238 0.2062348  0.20613821 ... 0.19698819 0.12445509 0.14338457]]
1
The 

In [72]:
U.argmax(axis=0).reshape(800,1)

array([[2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
    